import axios from "axios";
import Head from "next/head";
import { apiKey } from "../apiKey.js";

// Components
import Card from "../components/Card";

const pictures = ({ galaxy }) => {
  console.log(galaxy);
  return (
    <div>
      <Head>
        <title>The Galaxy || Picture of the Day</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card galaxy={galaxy} />
    </div>
  );
};

export const getStaticProps = async () => {
  const galaxy = await axios
    .get(`https://api.nasa.gov/planetary/apod?api_key=${apiKey}`)
    .then((res) => res.data);

  return {
    props: {
      galaxy,
    },
  };
};

export default pictures;
