import Head from "next/head";
import { useRouter } from "next/router";

const card = () => {
  const router = useRouter();
  const { id } = router.query;
  return (
    <>
      <Head>
        <title>Picture of the Day || Info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>This picture was taken on {id}</p>
      </div>
    </>
  );
};

export default card;
